name: Flutter CI

on:
  push:
    branches: [ master ] # 複数PRを同時にマージしたとき等のため
  pull_request:
    branches: [ master ] # masterへのPRにのみテストを実行

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --line-length 1000 --output=none --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test
